### ISSUE TITLE
Release version not working

### ISSUE THREAD

**Issue by JohnRayson** [VincentVancalbergh/NeedToKnow_Classic#1]
The version in NeedToKnow.4.0.28.Classic.zip doesn't seem to work, doesn't even appear in the AddOns list, the source code version does work though

**Comment by VincentVancalbergh** [comment]
The files weren't in a NeedToKnow folder.
Can you download and try again and let me know?

**Comment by JohnRayson** [comment]
Thanks @VincentVancalbergh It works now.

Do you know if there are any rules regarding the folder names for the addons. 
I tried renaming the folder to a couple of diffent variations. 
The actual folder / files structure looks the same. 
If it was just a folder issue then I'm pust puzzled as to why I couldn't get it work but could get the source files version to work.

**Comment by VincentVancalbergh** [comment]
I believe the folder and the .toc file need to match.
