### ISSUE TITLE
Bars spontaniously not ticking, drag icons all over the place

### ISSUE THREAD

**Issue by ghost** [VincentVancalbergh/NeedToKnow_Classic#4]
Since the latest patch, the bars are not ticking / running in a non repeatable pattern.
Means: Sometimes it works fine, sometimes not. 
Also, the icons to resize / drag the bars are randomly spread around the screen.

Is the addon still maintained by you?

Thanks

**Comment by JohnRayson** [comment]
Hi Paulbsh

I have issued a Pull request to resolve issues but Vincent has yet to accept them
The version that I'm using is available here:
[https://github.com/JohnRayson/NeedToKnow_Classic/archive/v1.0.zip](https://github.com/JohnRayson/NeedToKnow_Classic/archive/v1.0.zip)

Save / Extract the .zip - and then copy the NeedToKnow folder into you <WOW _classic_>/interface/addons folder. Existing configs will be retained.

**Comment by VincentVancalbergh** [comment]
I've issued a new release that should be more flexible with checking the build version.

**Comment by VincentVancalbergh** [comment]
I don't know why I didn't get notified of these issues..
